# Generated by Django 5.2.4 on 2025-07-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0004_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='9999999999', max_length=15),
        ),
    ]
