# Generated by Django 5.2.4 on 2025-07-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0005_alter_user_managers_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('customer', 'Customer')], max_length=10),
        ),
    ]
