# Generated by Django 5.2.4 on 2025-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='9999999999', max_length=15),
        ),
    ]
