# Generated by Django 5.2.4 on 2025-07-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0009_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
    ]
