# Generated by Django 5.2.4 on 2025-07-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0014_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='tocken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
