# Generated by Django 5.2.4 on 2025-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0017_login_phone_alter_login_password_alter_login_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
