# Generated by Django 5.2.4 on 2025-07-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0018_alter_login_password_alter_login_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='phone',
        ),
    ]
