# Generated by Django 5.2.4 on 2025-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0019_remove_login_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
