# Generated by Django 5.2.4 on 2025-08-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0021_alter_login_password_alter_login_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tocken',
            new_name='token',
        ),
    ]
