# Generated by Django 5.2.4 on 2025-08-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0022_rename_tocken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='item_name',
            field=models.CharField(default='Unnamed Item', max_length=100),
        ),
    ]
