# Generated by Django 5.2.4 on 2025-08-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0023_remove_menu_image_remove_menu_name_menu_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='item_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='Unnamed Item', max_length=100),
            preserve_default=False,
        ),
    ]
