# Generated by Django 5.2.4 on 2025-08-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0024_remove_menu_item_name_menu_image_menu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('drinks', 'Drinks')], max_length=20)),
                ('image', models.ImageField(upload_to='menu_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='menu',
        ),
    ]
