# Generated by Django 5.2.4 on 2025-08-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0026_mealtoken_menuitem_order_orderitem_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
