# Generated by Django 5.2.4 on 2025-08-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0029_rename_created_at_order_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='date_available',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Drinks', 'Drinks')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
