# Generated by Django 5.2.4 on 2025-08-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0030_menuitem_date_available_menuitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('drinks', 'Drinks')], default='lunch', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('drinks', 'Drinks')], max_length=50),
        ),
    ]
