# Generated by Django 5.2.4 on 2025-08-31 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0031_menuitem_meal_type_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='meal_type',
        ),
    ]
