# Generated by Django 5.2.4 on 2025-08-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0032_remove_menuitem_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('snacks', 'snacks'), ('drinks', 'drinks')], max_length=50),
        ),
    ]
