# Generated by Django 5.2.4 on 2025-08-31 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0034_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='status',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='date_available',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
